services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-analytics-backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-analytics-frontend
    ports:
      - "5035:80"
    depends_on:
      - backend
    restart: unless-stopped
